repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      # Executa o linter e corrige problemas automaticamente
      - id: ruff
        args: [--fix]
      # Executa o formatador de código padronizado
      - id: ruff-format