repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 4efeb931d635ed3e57749de4326b752b345c8372 # v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49 # v0.16.5
    hooks:
      # Run the linter and automatically fix supported issues
      - id: ruff
        args: [--fix]
      # Run the standard code formatter
      - id: ruff-format
