transformations:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID', 'projetodbt-479518') }}"
      dataset: alphavantage
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '/opt/airflow/config/gcp_credentials.json') }}"
      location: US
      timeout_seconds: 300
      priority: interactive
      retries: 1
