transformations:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: alphavantage_dev
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '/opt/airflow/gcp_key.json') }}"
      location: US
      timeout_seconds: 300
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: alphavantage
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '/opt/airflow/gcp_key.json') }}"
      location: US
      timeout_seconds: 300
      priority: interactive
      retries: 1

    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: alphavantage_ci
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '/opt/airflow/gcp_key.json') }}"
      location: US
      timeout_seconds: 300
      priority: interactive
      retries: 1

    docs:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID', 'public-docs') }}"
      dataset: alphavantage_docs
      threads: 1
      location: US
      timeout_seconds: 300
      priority: interactive
