import json
import logging
import os
import sys
from datetime import UTC, datetime


def setup_logger(file_name="extraction.log"):
    """
    Configure and return a logger formatted for stdout.
    The file uploaded to GCS contains only the structured entries
    generated by log_extraction(), without narrative console messages.
    """
    logger = logging.getLogger("extraction_logger")
    logger.setLevel(logging.INFO)
    logger.log_file = file_name

    # Avoid duplicate handlers when the logger is already configured.
    if not logger.handlers:
        stream_handler = logging.StreamHandler(sys.stdout)
        stream_handler.setFormatter(logging.Formatter("%(message)s"))
        logger.addHandler(stream_handler)

    return logger


def log_extraction(
    logger,
    status,
    stage_location_bucket,
    last_updated,
    endpoint,
    symbol,
    rows=0,
    size=0.0,
    time_seconds=0.0,
    error_message=None,
):
    """
    Write a structured JSON entry to the pipeline log file.
    Keep the GCS log file as strict JSON Lines (NDJSON)
    with only the metadata for each extraction.
    """
    log_entry = {
        "timestamp": datetime.now(UTC).isoformat(),
        "event": "ticker_extraction",
        "run_id": getattr(logger, "run_id", None) if logger else None,
        "status": status,
        "stage_location_bucket": stage_location_bucket,
        "last_updated": last_updated,
        "endpoint": endpoint,
        "symbol": symbol,
        "rows_processed": rows,
        "size_mb": size,
        "time_seconds": time_seconds,
        "error_message": str(error_message) if error_message else None,
    }

    _write_log_entry(logger, log_entry)


def log_batch_summary(logger, summary: dict) -> None:
    """Append one auditable summary for the complete endpoint batch."""
    log_entry = {
        "timestamp": datetime.now(UTC).isoformat(),
        "event": "batch_summary",
        **summary,
    }
    _write_log_entry(logger, log_entry)


def _write_log_entry(logger, log_entry: dict) -> None:
    log_file = getattr(logger, "log_file", "extraction.log") if logger else "extraction.log"
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")


def upload_and_clean_log(gcp_loader, local_log_file, destination_log_path):
    """
    Upload the local log file to GCS and remove the local copy.
    Log a warning without stopping the pipeline when the file is missing or upload fails.
    """
    log_uploaded = False  # Keep the flag initialized for every branch.

    if not os.path.exists(local_log_file):
        logging.warning(f"Log file not found; upload skipped: {local_log_file}")
        return

    try:
        gcp_loader.upload_file(local_log_file, destination_log_path)
        log_uploaded = True
    except Exception as e:
        # A log upload failure must not stop the main pipeline.
        logging.warning(f"Failed to upload log to {destination_log_path}: {e}")

    if log_uploaded:
        os.remove(local_log_file)
        logging.info(f"Log uploaded to {destination_log_path} and removed locally.")
    else:
        logging.warning(f"Log was not uploaded to GCS. Local file retained at: {local_log_file}")
